# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brain Crumbs
subtitle: 
name: André Pereira
logo: "/assets/images/logo.png"
email:
description: "Tech thoughs from another geek on the internet"
twitter_username: pereira__a
github_username: pereira-a
minimal_mistakes_skin: "contrast" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
locale: "en"
url: https://pereira-a.github.io
baseurl: /brain-crumbs
repository: pereira-a/brain-crumbs
timezone: Europe/Lisbon

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name     : "André Pereira"
  avatar   : "/assets/images/avatar.jpg"
  bio      : "Your typical Software Engineer from next door"
  location : Portugal
  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pereira__a"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pereira-a"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andr%C3%A9-pereira-8bb9a3230/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pereira__a"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pereira-a"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andr%C3%A9-pereira-8bb9a3230/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Comments provider
comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOHu90Nw # Shown during giscus setup at https://giscus.app
    category_name        : Announcements # Full text name of the category
    category_id          : DIC_kwDOHu90N84CQigC # Shown during giscus setup at https://giscus.app
    discussion_term      : pathname # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : light # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

# Search Engine Optimization
google_site_verification: "L2LYYDHg_ZH0geZYujw97x-z54s4_k1rQ0LHgJsC4V0"
# Finish big verification. Webmaster Tools are having a momentary issue
# bing_site_verification: "0FC3FD70512616B052E755A56F8952D"

# Open Graph
twitter_username: pereira__a
og_image: "/assets/images/logo.png"

# Google Knowledge
social:
  type:  Person # Person or Organization (defaults to Person)
  name:  André Pereira # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/pereira__a"
    - "https://www.instagram.com/andr3w_pereira/"
    - "https://www.linkedin.com/in/andr%C3%A9-pereira-8bb9a3230/"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-DT2Z0RSND5"
    anonymize_ip: false # default